Rename en.json to en.json5
getodk/central-frontend pull request #375
Opened 2020-09-08 01:54 UTC by matthew-white

2020-09-14 17:26 UTC, lognaturel approved these changes
Weird things happened.

2020-09-14 17:30 UTC, lognaturel reviewed
I see you're not renaming files for locales other than `en`. I think the correct files will be generated on the next language import. But won't the stale `.json` files also remain? Seems easier to rename them here.

2020-09-14 19:07 UTC, matthew-white commented
One of the main reasons I made this change was to improve the display of `en.json5` in GitHub: after this PR, comments will no longer be highlighted as syntax errors. But I actually like that `en.json5` ends up with a different file extension from the other locale files, and my thinking is that the other files will continue to have a `.json` extension. `en.json5` is the only locale file that is actually JSON5: it's the source locale, so it's the only locale file with comments. Because of that, it's also loaded differently: `en.json5` is loaded in a different place from the other locale files and using a different loader (the `json5-loader`). I think that with this change, the locale files will also nicely parallel the i18n custom blocks: in each component, the first i18n block is the source locale and JSON5, and the second i18n block is the translated locales and JSON.

2020-09-14 19:13 UTC, matthew-white commented
I just merged #376, and it looks like there are no merge conflicts. 🎊

2020-09-14 21:31 UTC, lognaturel commented on bin/util/transifex.js
> +    fs.readFileSync(`${localesDir}/${sourceLocale}.json5`).toString(),
This is what made me think all files were expected to have a `json5` extension.

2020-09-14 21:35 UTC, lognaturel commented
Thanks for the extra information. Always helpful to get a small PR description when we do async review! It can also helpful for future archaeology to capture why things are being done.

All that makes sense, but I'm still uncertain about one change I've marked inline.

2020-09-14 21:37 UTC, lognaturel requested changes
We're still getting me up to speed and I can't seem to dismiss my review.

2020-09-15 13:20 UTC, matthew-white commented
> Thanks for the extra information. Always helpful to get a small PR description when we do async review!

I tried to add some context in the commit message, but I can see now that that was rather succinct. 😅

> All that makes sense, but I'm still uncertain about one change I've marked inline.

Is that the comment above about the .json5 extension in `readSourceMessages()`? Is that resolved now? You’re exactly right that it’s .json5 there because it’s reading the source locale: `writeTranslations()` outputs .json files for the translated locales.

2020-09-15 13:27 UTC, lognaturel commented on bin/util/transifex.js
> +    fs.readFileSync(`${localesDir}/${sourceLocale}.json5`).toString(),
Sourcelocale is a constant set to ‘en’

2020-09-15 13:28 UTC, lognaturel approved these changes

2020-09-15 13:36 UTC, merged